# Generated by Django 4.1.2 on 2022-10-24 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_myuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='username',
        ),
    ]
