# Generated by Django 4.1.2 on 2022-11-05 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0005_product_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
