# Generated by Django 4.1.2 on 2022-12-15 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0009_arrival'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'My Category', 'verbose_name_plural': 'My Categorys'},
        ),
    ]
